### ISSUE TITLE
Keeping all artifacts 

### ISSUE THREAD

**Issue by Christopm** [MoeLa/DominationsMuseumCrawler#10]
Hello and thank you for creating this tool!

The program runs on its own, but it doesn't sell any artifacts. I have seven separate rules running, with several properties in each rule, but the program doesn't auto-sell any of them, even if they don't meet the rule.  With 4 out of 5 matches selected. 

I'm running both programs in the same language (English). Operating on a Google Pixel 3a XL. 

Also, is there any way to donate money to you for this work?

**Comment by Christopm** [comment]
I changed it to Dutch and seems to be working fine now.

**Comment by MoeLa** [comment]
Hey Christopm,
thank you for the bug report. Right now, I don't have the time to dig into it, but I will. Please use the workaround you've provided.

I'm not taking donations... but you can donate in my spirit to any senseful cause, if you like ;-)

By the way: "Deutsch" = German (in German), "Dutch" = the language spoken in the Netherlands.

**Comment by Christopm** [comment]
Oh, I didn’t know the difference. “Stupid Americans”

Thanks for getting back to me and, I must say, phenomenal job Sir!!!!

On Jul 6, 2022, at 20:18, Moe ***@***.***> wrote:

﻿

Hey Christopm,
thank you for the bug report. Right now, I don't have the time to dig into it, but I will. Please use the workaround you've provided.

I'm not taking donations... but you can donate in my spirit to any senseful cause, if you like ;-)

By the way: "Deutsch" = German (in German), "Dutch" = the language spoken in the Netherlands.

**Comment by Christopm** [comment]
Sorry, changed to Deutsch, not Dutch. I'm showing my ignorance of the foreign languages
