### ISSUE TITLE
Newest release installation fails

### ISSUE THREAD

**Issue by helsko** [MoeLa/DominationsMuseumCrawler#15]
1.1.2 apk installation fails on LDPlayer9 and Bluestacks 5. 
1.1.0 installs and runs just fine. 

LDPlayer reports that file is already used in another program, Bluestacks with general error.

edit: just found the 1.1.3 rebuild, will test that one

**Comment by helsko** [comment]
1.1.3 works with Bluestacks 5.12.0 and English. Just a few false positives here and there, I'll try out German and compare.
A nice to have feature would be to be able to filter for % values.
Thanks for this gem of an app!

**Comment by Lzh-qwe** [comment]
How did you adjust the resolution of Bluestacks, or change other settings, to make version 1.1.3 work? It doesn’t run on my end.

**Comment by Lzh-qwe** [comment]
How did you get it to run on an Android emulator, such as LDPlayer 9? It doesn’t launch on my end—there’s no response when I try to start it.

**Comment by Lzh-qwe** [comment]
How did you get it to run on an Android emulator, such as LDPlayer 9? It doesn’t launch on my end—there’s no response when I try to start it. @helsko
