### ISSUE TITLE
"Developer warning"

### ISSUE THREAD

**Issue by Unveinst** [MoeLa/DominationsMuseumCrawler#17]
Thanks for the version 1.1.3 in the other issue thread, it works for me. Both in English and in German.

On first use, there is a warning to the developers during the superuser request: "android.permission.ACCESS_SUPERUSER not declared in manifest". Is there anything against adding this?

Perhaps this would also prevent the constant toast indicating that the app has been granted superuser. These toasts disrupt image recognition when they partially cover the sell and keep buttons.

**Comment by MoeLa** [comment]
Yeah, I think there isn't anything against this.

By the way, you can disable the toasts in magisk:
- select "Superuser" in the bottom list (between Home and Logs)
- tip on the Museum Crawler > some additional options pop out
- tap on Notifications to grey it out

**Comment by MoeLa** [comment]
Ok, I've dug into that topic. I found this here: https://su.chainfire.eu/#updates-permission
I think, you should first try to move from an abandoned SuperSu to Magisk (or something similar).
